### ISSUE TITLE
Banner subtitles

### ISSUE THREAD

**Issue by lalvarezguillen** [lalvarezguillen/lalvarezguillen.github.io#1]
![image](https://user-images.githubusercontent.com/16627437/67159684-1195d780-f340-11e9-945e-48b4e6166d9d.png)

We need to dedice if we want to keep the subtitles of the banners. If we keep them, we need to create content for them

**Comment by Aymenuc** [comment]
what do you think of this ?:

From the heart of the desert, we bring you a 100% artisanal and organic production.

**Comment by Aymenuc** [comment]
I propose changing the main title to: 

> premium natural products, from the oasis to you.

**Comment by lalvarezguillen** [comment]
Updated title and subtitle of banner
