### ISSUE TITLE
About Us section of homepage

### ISSUE THREAD

**Issue by lalvarezguillen** [lalvarezguillen/lalvarezguillen.github.io#3]
![image](https://user-images.githubusercontent.com/16627437/67159705-5752a000-f340-11e9-9647-7f331758f7fc.png)

The About Us section of the homepage needs content: images and text

**Comment by Aymenuc** [comment]
**I propose to change "about us" with "our concept"
for the content I propose the following:**
![IMG_20151005_091004_PerfectlyClear](https://user-images.githubusercontent.com/56792561/67209074-fa75e900-f416-11e9-8e44-1204fd994309.jpg)



We offer you premium quality of dates and dates derived products "100% natural" from the heart of the Algeria Sahara. Our palm grove is located in the region of Tolga, Biskra in Algeria, among the best soils for dates in the region of North Africa. We are keen to introduce the best existing quality of this prestigious fruit, "Deglet Nour" or "fingers of light", characterized by its transparent shape, revealing its nucleus. in addition to a range of organic products.
We give you the chance to experience the original "queen of dates", directly from the oasis to you. 
**I propose the attached picture**

**Comment by lalvarezguillen** [comment]
@Aymenuc you can see the updated content here: https://lalvarezguillen.github.io/index.html
