### ISSUE TITLE
What We Do section of homepage

### ISSUE THREAD

**Issue by lalvarezguillen** [lalvarezguillen/lalvarezguillen.github.io#4]
![image](https://user-images.githubusercontent.com/16627437/67159717-76e9c880-f340-11e9-9d4b-706676ff7628.png)

1. We need to decide if we maintain the text under this section's title. If affirmative, we need to craft the content.

2. Organic, Locally Made, and Eco Friendly contain some text. We should decide if we keep text there, and craft those texts.

**Comment by Aymenuc** [comment]
for the text what we do I propose the following: 
To preserve the unique and optimal taste of the queen of dates, the fruit is collected between the period of October and November. After, our dates are stored manually with the necessary delicacy. 
In a 100% organic process, a range of natural products are derived from the dates as Low-Sugar Alternatives to Your Favorite Foods. 
We are committed to providing you with the highest quality for the best competitive price in the market, our services are offered to more than 68 countries in the world. 
Flexible, available and responsive, are our ethics to give the highest priority for the satisfaction of our costumers.

**Comment by lalvarezguillen** [comment]
* Updated `What We Do` section text
* Updated Organic icon
* Removed text under icons
