### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by lalvarezguillen** [lalvarezguillen/lalvarezguillen.github.io#5]
We need a logo for the website

**Comment by Aymenuc** [comment]
I propose this logo: 
meaning: the company's name is naourass, which is a type of sea bird that travels overseas, I tried to demonstrate that in the logo referring to "cargo" "services" "shipping" "exporting" overseas in blue.
the camel referring to the desert related products, background colors refer to "sand and sea" from the oasis to you.   
![logo 2](https://user-images.githubusercontent.com/56792561/67209436-a0295800-f417-11e9-9340-f8bcf8d96b07.PNG)

**Comment by lalvarezguillen** [comment]
Logo was added
