### ISSUE TITLE
About Us page

### ISSUE THREAD

**Issue by lalvarezguillen** [lalvarezguillen/lalvarezguillen.github.io#6]
We need English translation of the About Us page. We also need an image for this page
![image](https://user-images.githubusercontent.com/16627437/67159800-97fee900-f341-11e9-8419-754bab33a2ce.png)

**Comment by Aymenuc** [comment]
I propose a different text: 
"Naourass Import-Export" is a company specialized in the exportation of organic agricultural products, mainly Algerian dates, and vegetables, as well as all the dates derived natural products.

Our dates are brought to you directly from the vast oasis of the Algerian desert from the region of  "Beskra",  known as one of the best soils for growing dates in the world. ensuring the delivery of a superior quality to our clients.  

Highly competent professionals, we ensure a direct connection between the supplier and the customer, we guarantee a high quality/price ratio of the delivered products and the full satisfaction of the customer.

We are committed to working in partnership with trustful growers who have been fulfilling the market requirements for years.
We offer you unique quality and taste at any time of the year, our products are handled in an organic and non-chemical process of treatment. we guarantee you optimal quality for the best price.
![deglet-noor-1](https://user-images.githubusercontent.com/56792561/67219564-93613000-f428-11e9-9dd7-2dfac97476cc.jpg)

**Comment by lalvarezguillen** [comment]
@Aymenuc the page was updated, you can see it here: https://lalvarezguillen.github.io/about
